version: "3.8"
services:
  app:
    build: .
    container_name: "cv_builder"
    links:
      - db
    ports:
      - "52000:5000"
    working_dir: /datadrive
    volumes:
      - .:/datadrive
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: cv_builder
      MYSQL_CHARSET: utf8mb4

  db:
    image: mysql
    container_name: "cv_builder_db"
    restart: always
    command: --init-file /db/init.sql --default-authentication-plugin=mysql_native_password
    ports:
    - "52001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - ./db/init.sql:/db/init.sql
    - cv-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: "cv_builder_adminer"
    restart: always
    ports:
      - 52002:8080

volumes:
  cv-data: